.job_template: &defaults  # Hidden key that defines an anchor named 'job_definition'
  image: ricking06/darkphy-docker
  services:
    - mysql/mysql-server:8.0.0
    - redis

variables:
  MIX_ENV: "test"
  MYSQL_DATABASE: darkphy
  MYSQL_USER: mother
  MYSQL_PASSWORD: fucker
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"


stages:
  - test


#mysql_build:
#  <<: *defaults
#  stage: mysql_build
#  variables:
#    MYSQL_ROOT_USER: root
#    MYSQL_ROOT_PASSWORD: password
#  before_script:
#    - mysql --version
#  script:
#    - echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

test:
  <<: *defaults
  stage: test
  before_script:
    # Setup phoenix dependencies
    - mysql --version
    - service mysql start
    - mix deps.get --only test
  script:
    - mix test
