.job_template: &defaults  # Hidden key that defines an anchor named 'job_definition'
  image: ricking06/darkphy-docker
  variables:
    MIX_ENV: "test"
    MYSQL_DATABASE: darkphy
    MYSQL_USER: mother
    MYSQL_PASSWORD: fucker
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: password
    MYSQL_HOSTNAME: 127.0.0.1
  services:
    - mysql




stages:
  - mysql_build
  - test_elixir
  - test_javascript


mysql_build:
  <<: *defaults
  stage: mysql_build
  variables:
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: password
  before_script:
    - mysql --version
  script:
    - echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

test_elixir:
  <<: *defaults
  stage: test_elixir
  before_script:
    # Setup phoenix dependencies
    - mysql --version
    - ps aux | grep mysql
    #- echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host="${MYSQL_HOSTNAME}" "${MYSQL_DATABASE}"
    #- echo "show processlist" | mysql -u root
    #- echo "CREATE USER '${MYSQL_USER}'@'${MYSQL_HOSTNAME}' IDENTIFIED BY '${MYSQL_PASSWORD}'" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host="${MYSQL_HOSTNAME}"
    # echo "CREATE DATABASE IF NOT EXISTS `gitlabhq_production` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_general_ci`"
    - mix deps.get --only test
  script:
    - mix test

test_javascript:
    <<: *defaults
    stage: test_javascript
    before_script:
      - cd
    script:
      - cd apps/darkphy_web/assets/auth/
      - yarn install
      - yarn run test
