.job_template: &defaults  # Hidden key that defines an anchor named 'job_definition'
  image: ricking06/darkphy-docker
  variables:
    MIX_ENV: "test"
    MYSQL_DATABASE: darkphy
    MYSQL_USER: mother
    MYSQL_PASSWORD: fucker
    MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: password
    MYSQL_HOSTNAME: mysql
  services:
    - mysql




stages:
#  - mysql_build
  - test_javascript
  - test_elixir


#mysql_build:
#  <<: *defaults
#  stage: mysql_build
#  variables:
#    MYSQL_ROOT_USER: root
#    MYSQL_ROOT_PASSWORD: password
#  before_script:
#    - mysql --version
#  script:
#    - echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

test_elixir:
  <<: *defaults
  stage: test_elixir
  before_script:
    # Setup phoenix dependencies
    - mysql --version
    #- echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host="${MYSQL_HOSTNAME}" "${MYSQL_DATABASE}"
    #- echo "show processlist" | mysql -u root
    - echo "SELECT 'OK';" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host="${MYSQL_HOSTNAME}" "${MYSQL_DATABASE}"
    - echo "CREATE USER 'mother'@'mysql' IDENTIFIED BY 'fucker'" | mysql --user="${MYSQL_ROOT_USER}" --password="${MYSQL_ROOT_PASSWORD}" --host="${MYSQL_HOSTNAME}"
    - echo "SELECT 'OK';" | mysql --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" --host="${MYSQL_HOSTNAME}" "${MYSQL_DATABASE}"
    - echo "SHOW GLOBAL VARIABLES LIKE 'PORT';" | mysql --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" --host="${MYSQL_HOSTNAME}" "${MYSQL_DATABASE}"
    #- echo "CREATE DATABASE IF NOT EXISTS darkphy" | mysql --user="${MYSQL_USER}" --password="${MYSQL_PASSWORD}" --host=mysql
    - mix deps.get --only test
  script:
    - mix test
  cache:
    untracked: true
    paths:
      - _build
      - deps

test_javascript:
    <<: *defaults
    stage: test_javascript
    before_script:
      - cd
    script:
      - cd /builds/darkphy/darkphy_apps/apps/darkphy_web/assets/apps/auth/
      - yarn install
      - yarn run test
    cache:
      untracked: true
      paths:
        - node_modules
