image: elixir:latest

services:
  - mysql
  - redis


variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: darkphy
  MYSQL_USER: mother
  MYSQL_PASSWORD: fucker

connect:
  image: mysql
  
variables:
  MIX_ENV: "test"

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get --only test

test:
  script:
    - mix test
