image: elixir:latest

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: darkphy
  MYSQL_USER: mother
  MYSQL_PASSWORD: fucker
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: password
  MIX_ENV: "test"

services:
  - mysql
  - redis

before_script:
  # Setup phoenix dependencies
  - apt-get update
  - service mysql start
  - mix deps.get --only test

connect:
  image: mysql
  script:
  - echo "CREATE user '$MYSQL_USER'@'mysql' IDENTIFIED BY '$MYSQL_PASSWORD'" | mysql --user="$MYSQL_ROOT_USER" --password="$MYSQL_ROOT_PASSWORD"
  - echo "CREATE DATABASE IF NOT EXISTS `$MYSQL_DATABASE` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_general_ci`"" | mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD"

test:
  script:
    - mix test
