FROM elixir:latest

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
WORKDIR /app
COPY ./darkphy_apps.tar.gz ./
RUN tar xfz darkphy_apps.tar.gz
ENTRYPOINT ["bin/darkphy_apps"]
